In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

In [2]:
from sklearn.linear_model import LogisticRegression
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.metrics import r2_score,mean_absolute_error,mean_squared_error
from sklearn.tree import DecisionTreeClassifier
from sklearn.metrics import accuracy_score,confusion_matrix

In [3]:
df = pd.read_csv("F:\PYTHAN\PYTHAN\iNeuron\ML\CampusX\Logistic_Regression\heart_disease_data.csv")

In [4]:
df.shape

(303, 14)

In [5]:
df.head(2)

age  sex  cp  trestbps  chol  fbs  restecg  thalach  exang  oldpeak  slope  \
0   63    1   3       145   233    1        0      150      0      2.3      0   
1   37    1   2       130   250    0        1      187      0      3.5      0   

   ca  thal  target  
0   0     1       1  
1   0     2       1

In [6]:
x = df.iloc[:,:13]
y = df.iloc[:,-1]

In [7]:
x.head()

age  sex  cp  trestbps  chol  fbs  restecg  thalach  exang  oldpeak  slope  \
0   63    1   3       145   233    1        0      150      0      2.3      0   
1   37    1   2       130   250    0        1      187      0      3.5      0   
2   41    0   1       130   204    0        0      172      0      1.4      2   
3   56    1   1       120   236    0        1      178      0      0.8      2   
4   57    0   0       120   354    0        1      163      1      0.6      2   

   ca  thal  
0   0     1  
1   0     2  
2   0     2  
3   0     2  
4   0     2

In [8]:
y.head()

0    1
1    1
2    1
3    1
4    1
Name: target, dtype: int64

In [9]:
x_train,x_test,y_train,y_test = train_test_split(x,y,test_size = 0.2, random_state = 2)

In [10]:
print(x_train.shape,x_test.shape)
print(y_train.shape,y_test.shape)

(242, 13) (61, 13)
(242,) (61,)


In [11]:
lgr = LogisticRegression()
dt = DecisionTreeClassifier()

In [12]:
dt.fit(x_train,y_train)

DecisionTreeClassifier()

In [13]:
lgr.fit(x_train,y_train)

C:\Users\vishal\anaconda3\lib\site-packages\sklearn\linear_model\_logistic.py:763: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(


LogisticRegression()

In [14]:
y_pred_lgr = lgr.predict(x_test)
y_pred_dt = dt.predict(x_test)

In [15]:
print("Accuracyscore of Logistic Reg", accuracy_score(y_test,y_pred_lgr))
print("Accuracyscore of Decision Tree", accuracy_score(y_test,y_pred_dt))

Accuracyscore of Logistic Reg 0.9016393442622951
Accuracyscore of Decision Tree 0.8688524590163934


In [18]:
confusion_matrix(y_test,y_pred_lgr)# confusion matrix for Logistic

array([[26,  6],
       [ 0, 29]], dtype=int64)

In [25]:
confusion_matrix(y_test,y_pred_dt)# confusion matrix for decision tree

array([[25,  7],
       [ 1, 28]], dtype=int64)

In [21]:
# import metrix of logistic
from sklearn.metrics import precision_score,recall_score,f1_score

In [24]:
print("precision score :", precision_score(y_test,y_pred_lgr))
print("Recall score :", recall_score(y_test,y_pred_lgr))
print("F1 score :" , f1_score(y_test,y_pred_lgr))

precision score : 0.8285714285714286
Recall score : 1.0
F1 score : 0.90625


In [27]:
print("precision score :", precision_score(y_test,y_pred_dt))
print("Recall score :", recall_score(y_test,y_pred_dt))
print("F1 score :" , f1_score(y_test,y_pred_dt))

precision score : 0.8
Recall score : 0.9655172413793104
F1 score : 0.8750000000000001


# Multiclass precision and recall

In [31]:
df1 = pd.read_csv("F:/PYTHAN/PYTHAN/iNeuron/ML/CampusX/Logistic_Regression/digit_recognizer/train.csv")

In [32]:
df1.head()

label  pixel0  pixel1  pixel2  pixel3  pixel4  pixel5  pixel6  pixel7  \
0      1       0       0       0       0       0       0       0       0   
1      0       0       0       0       0       0       0       0       0   
2      1       0       0       0       0       0       0       0       0   
3      4       0       0       0       0       0       0       0       0   
4      0       0       0       0       0       0       0       0       0   

   pixel8  ...  pixel774  pixel775  pixel776  pixel777  pixel778  pixel779  \
0       0  ...         0         0         0         0         0         0   
1       0  ...         0         0         0         0         0         0   
2       0  ...         0         0         0         0         0         0   
3       0  ...         0         0         0         0         0         0   
4       0  ...         0         0         0         0         0         0   

   pixel780  pixel781  pixel782  pixel783  
0         0         0         0         0  
1         0         0         0         0  
2         0         0         0         0  
3         0         0         0         0  
4         0         0         0         0  

[5 rows x 785 columns]

In [33]:
df1.head(2)

label  pixel0  pixel1  pixel2  pixel3  pixel4  pixel5  pixel6  pixel7  \
0      1       0       0       0       0       0       0       0       0   
1      0       0       0       0       0       0       0       0       0   

   pixel8  ...  pixel774  pixel775  pixel776  pixel777  pixel778  pixel779  \
0       0  ...         0         0         0         0         0         0   
1       0  ...         0         0         0         0         0         0   

   pixel780  pixel781  pixel782  pixel783  
0         0         0         0         0  
1         0         0         0         0  

[2 rows x 785 columns]

In [42]:
df1['label'].unique() # output column has 10 unique values.

array([1, 0, 4, 7, 3, 5, 8, 9, 2, 6], dtype=int64)

In [43]:
# seprate out input and output columns
x1 = df1.iloc[:,1:]
y1 = df1.iloc[:,0]

In [44]:
x1

pixel0  pixel1  pixel2  pixel3  pixel4  pixel5  pixel6  pixel7  pixel8  \
0           0       0       0       0       0       0       0       0       0   
1           0       0       0       0       0       0       0       0       0   
2           0       0       0       0       0       0       0       0       0   
3           0       0       0       0       0       0       0       0       0   
4           0       0       0       0       0       0       0       0       0   
...       ...     ...     ...     ...     ...     ...     ...     ...     ...   
41995       0       0       0       0       0       0       0       0       0   
41996       0       0       0       0       0       0       0       0       0   
41997       0       0       0       0       0       0       0       0       0   
41998       0       0       0       0       0       0       0       0       0   
41999       0       0       0       0       0       0       0       0       0   

       pixel9  ...  pixel774  pixel775  pixel776  pixel777  pixel778  \
0           0  ...         0         0         0         0         0   
1           0  ...         0         0         0         0         0   
2           0  ...         0         0         0         0         0   
3           0  ...         0         0         0         0         0   
4           0  ...         0         0         0         0         0   
...       ...  ...       ...       ...       ...       ...       ...   
41995       0  ...         0         0         0         0         0   
41996       0  ...         0         0         0         0         0   
41997       0  ...         0         0         0         0         0   
41998       0  ...         0         0         0         0         0   
41999       0  ...         0         0         0         0         0   

       pixel779  pixel780  pixel781  pixel782  pixel783  
0             0         0         0         0         0  
1             0         0         0         0         0  
2             0         0         0         0         0  
3             0         0         0         0         0  
4             0         0         0         0         0  
...         ...       ...       ...       ...       ...  
41995         0         0         0         0         0  
41996         0         0         0         0         0  
41997         0         0         0         0         0  
41998         0         0         0         0         0  
41999         0         0         0         0         0  

[42000 rows x 784 columns]

In [45]:
y1

0        1
1        0
2        1
3        4
4        0
        ..
41995    0
41996    1
41997    7
41998    6
41999    9
Name: label, Length: 42000, dtype: int64

In [46]:
print(x1.shape)
print(y1.shape)

(42000, 784)
(42000,)


In [47]:
x1_train,x1_test,y1_train,y1_test = train_test_split(x1,y1,test_size = 0.2, random_state  = 2)

In [48]:
print(x1_train.shape,y1_train.shape)
print(x1_test.shape,y1_test.shape)

(33600, 784) (33600,)
(8400, 784) (8400,)


In [49]:
log = LogisticRegression()

In [50]:
log.fit(x1_train,y1_train)

C:\Users\vishal\anaconda3\lib\site-packages\sklearn\linear_model\_logistic.py:763: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(


LogisticRegression()

In [51]:
y_pred_log = log.predict(x1_test)

In [53]:
print("Accuracy score :",accuracy_score(y1_test,y_pred_log))

Accuracy score : 0.9145238095238095


In [56]:
# all score is not calculate by averaging method, all score is claculated for each label of target column.
print("precision score :", precision_score(y1_test,y_pred_log, average = None))

print("recall score :", recall_score(y1_test,y_pred_log, average = None))

print("f1 score :", f1_score(y1_test,y_pred_log, average = None))

precision score : [0.94844125 0.95422177 0.91411043 0.90295858 0.93379791 0.8739255
 0.93262411 0.91235955 0.86318408 0.89320388]
recall score : [0.9634592  0.97505198 0.8986731  0.88310185 0.93925234 0.83676269
 0.94040524 0.930126   0.87515763 0.882494  ]
f1 score : [0.95589124 0.96452442 0.90632603 0.89291984 0.93651718 0.85494043
 0.93649852 0.92115712 0.86912962 0.88781665]


In [57]:
## all score is  calculate by averaging method
print("precision score :", precision_score(y1_test,y_pred_log, average = 'macro'))

print("recall score :", recall_score(y1_test,y_pred_log, average = 'macro'))

print("f1 score :", f1_score(y1_test,y_pred_log, average = 'macro'))

precision score : 0.9128827064397905
recall score : 0.9124484028871509
f1 score : 0.9125721045561429


In [60]:
confusion_matrix(y1_test,y_pred_log)

array([[791,   0,   1,   0,   1,   9,  11,   1,   6,   1],
       [  0, 938,   2,   4,   0,   3,   0,   3,  12,   0],
       [  2,   9, 745,  16,   9,   4,  13,  13,  15,   3],
       [  1,   4,  19, 763,   0,  36,   5,   5,  20,  11],
       [  2,   5,   4,   0, 804,   1,   7,   3,   9,  21],
       [  9,   3,   4,  23,  10, 610,  15,  10,  34,  11],
       [ 12,   4,  12,   1,   7,   8, 789,   0,   5,   1],
       [  3,   2,  13,   6,   4,   2,   0, 812,   2,  29],
       [ 11,  12,  13,  18,   1,  21,   6,   6, 694,  11],
       [  3,   6,   2,  14,  25,   4,   0,  37,   7, 736]], dtype=int64)

In [59]:
# now from sklearn one class is there for all report for metrics carried out at one time
from sklearn.metrics import classification_report
print(classification_report(y1_test,y_pred_log))


              precision    recall  f1-score   support

           0       0.95      0.96      0.96       821
           1       0.95      0.98      0.96       962
           2       0.91      0.90      0.91       829
           3       0.90      0.88      0.89       864
           4       0.93      0.94      0.94       856
           5       0.87      0.84      0.85       729
           6       0.93      0.94      0.94       839
           7       0.91      0.93      0.92       873
           8       0.86      0.88      0.87       793
           9       0.89      0.88      0.89       834

    accuracy                           0.91      8400
   macro avg       0.91      0.91      0.91      8400
weighted avg       0.91      0.91      0.91      8400

