In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import precision_score,recall_score,confusion_matrix
from sklearn.preprocessing import OneHotEncoder,LabelEncoder
import seaborn as sns


In [2]:
df = sns.load_dataset('iris')

In [3]:
df.head()

sepal_length  sepal_width  petal_length  petal_width species
0           5.1          3.5           1.4          0.2  setosa
1           4.9          3.0           1.4          0.2  setosa
2           4.7          3.2           1.3          0.2  setosa
3           4.6          3.1           1.5          0.2  setosa
4           5.0          3.6           1.4          0.2  setosa

In [4]:
df.shape

(150, 5)

In [5]:
encoder = LabelEncoder()

In [6]:
# output column (species) need to encode 
df['species'] = encoder.fit_transform(df['species'])

In [7]:
df.head()

sepal_length  sepal_width  petal_length  petal_width  species
0           5.1          3.5           1.4          0.2        0
1           4.9          3.0           1.4          0.2        0
2           4.7          3.2           1.3          0.2        0
3           4.6          3.1           1.5          0.2        0
4           5.0          3.6           1.4          0.2        0

In [8]:
df = df[['sepal_length', 'petal_length', 'species']] # we take only 2 input column and 1 output column

In [9]:
df.head()

sepal_length  petal_length  species
0           5.1           1.4        0
1           4.9           1.4        0
2           4.7           1.3        0
3           4.6           1.5        0
4           5.0           1.4        0

In [10]:
x = df.iloc[:,0:2]
y = df.iloc[:,-1]

In [11]:
x.head()

sepal_length  petal_length
0           5.1           1.4
1           4.9           1.4
2           4.7           1.3
3           4.6           1.5
4           5.0           1.4

In [12]:
y.head()

0    0
1    0
2    0
3    0
4    0
Name: species, dtype: int32

In [13]:
x_train,x_test,y_train,y_test = train_test_split(x,y,test_size = 0.2,random_state = 2)

In [14]:
print(x_train.shape,x_test.shape)
print(y_train.shape,y_test.shape)

(120, 2) (30, 2)
(120,) (30,)


In [15]:
log = LogisticRegression(multi_class= 'multinomial')

In [16]:
log.fit(x_train,y_train)

LogisticRegression(multi_class='multinomial')

In [17]:
y_pred = log.predict(x_test)

In [18]:
from sklearn.metrics import accuracy_score

In [19]:
accuracy_score(y_test,y_pred)

0.9666666666666667

In [20]:
confusion_matrix(y_test,y_pred)

array([[14,  0,  0],
       [ 0,  7,  1],
       [ 0,  0,  8]], dtype=int64)

In [21]:
#prediction of input data [3.4,2.7]
data_point = np.array([[3.4,2.7]])
log.predict_proba(data_point) # pridict all three species with value and we select max value

C:\Users\vishal\anaconda3\lib\site-packages\sklearn\base.py:464: UserWarning: X does not have valid feature names, but LogisticRegression was fitted with feature names
  warnings.warn(


array([[7.25957888e-01, 2.73627865e-01, 4.14246954e-04]])

In [22]:

log.predict(data_point) # pridict 1st value of above

C:\Users\vishal\anaconda3\lib\site-packages\sklearn\base.py:464: UserWarning: X does not have valid feature names, but LogisticRegression was fitted with feature names
  warnings.warn(


array([0])

In [25]:
pip install mlxtend

  Using cached mlxtend-0.22.0-py2.py3-none-any.whl (1.4 MB)
Note: you may need to restart the kernel to use updated packages.


In [24]:
from mlxtend.plotting import plot_decision_regions

plot_decision_regions(x.values,y.values, log,legend = 2)

plt.title('softmax on iris')
plt.xlabel('sepal length')
plt.ylabel('petal length')
plt.show

ModuleNotFoundError: No module named 'mlxtend'