In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import roc_curve,roc_auc_score


In [2]:
# import diabetes data set
df = pd.read_csv("F:\PYTHAN\PYTHAN\iNeuron\ML\CampusX\SVM_ROC\diabetes.csv")

In [3]:
df.head(2)

Pregnancies  Glucose  BloodPressure  SkinThickness  Insulin   BMI  \
0            6      148             72             35        0  33.6   
1            1       85             66             29        0  26.6   

   DiabetesPedigreeFunction  Age  Outcome  
0                     0.627   50        1  
1                     0.351   31        0

In [4]:
df.shape

(768, 9)

In [5]:
# splite data in to input data and target or output data
x = df.drop('Outcome',axis = 1)
y = df['Outcome']

In [6]:
x.head(2)

Pregnancies  Glucose  BloodPressure  SkinThickness  Insulin   BMI  \
0            6      148             72             35        0  33.6   
1            1       85             66             29        0  26.6   

   DiabetesPedigreeFunction  Age  
0                     0.627   50  
1                     0.351   31

In [7]:
y.head()

0    1
1    0
2    1
3    0
4    1
Name: Outcome, dtype: int64

In [8]:
# now data has divided n to train test
x_train,x_test,y_train,y_test = train_test_split(x,y,test_size = 0.2,random_state = 42)

In [9]:
print(x_train.shape,x_test.shape)
print(y_train.shape,y_test.shape)

(614, 8) (154, 8)
(614,) (154,)


In [10]:
log = LogisticRegression(max_iter=1000)

In [11]:
log.fit(x_train,y_train)

LogisticRegression(max_iter=1000)

In [12]:
y_pred=log.predict(x_test)

In [13]:
y_pred

array([0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 0, 1, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0,
       1, 0, 1, 1, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 0, 1, 1, 0,
       0, 1, 1, 0, 0, 1, 0, 1, 1, 0, 0, 0, 1, 0, 0, 1, 1, 0, 0, 0, 0, 1,
       0, 1, 0, 1, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 1, 0,
       0, 0, 0, 0, 0, 1, 1, 1, 0, 0, 1, 0, 1, 0, 1, 1, 1, 0, 0, 1, 0, 1,
       0, 0, 0, 1, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1,
       0, 0, 1, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0],
      dtype=int64)

In [14]:
# to find probability of person has dabetes or not
log.predict_proba(x_test)
#this give both value dabetes and not diabetes

array([[0.7240649 , 0.2759351 ],
       [0.81155898, 0.18844102],
       [0.88554825, 0.11445175],
       [0.83640039, 0.16359961],
       [0.52855384, 0.47144616],
       [0.55816729, 0.44183271],
       [0.984525  , 0.015475  ],
       [0.33916678, 0.66083322],
       [0.45849805, 0.54150195],
       [0.22273579, 0.77726421],
       [0.74403077, 0.25596923],
       [0.1026634 , 0.8973366 ],
       [0.66383196, 0.33616804],
       [0.69685399, 0.30314601],
       [0.91795232, 0.08204768],
       [0.61887387, 0.38112613],
       [0.86063033, 0.13936967],
       [0.92517714, 0.07482286],
       [0.13330902, 0.86669098],
       [0.43868758, 0.56131242],
       [0.79160036, 0.20839964],
       [0.92256854, 0.07743146],
       [0.46031971, 0.53968029],
       [0.90539699, 0.09460301],
       [0.46058403, 0.53941597],
       [0.11447099, 0.88552901],
       [0.87562827, 0.12437173],
       [0.96981444, 0.03018556],
       [0.74858002, 0.25141998],
       [0.8841397 , 0.1158603 ],
       [0.

In [19]:
# now We need only value of probality of person has dabetes
y_score = log.predict_proba(x_test)[:,0]

In [20]:
y_score 

array([0.7240649 , 0.81155898, 0.88554825, 0.83640039, 0.52855384,
       0.55816729, 0.984525  , 0.33916678, 0.45849805, 0.22273579,
       0.74403077, 0.1026634 , 0.66383196, 0.69685399, 0.91795232,
       0.61887387, 0.86063033, 0.92517714, 0.13330902, 0.43868758,
       0.79160036, 0.92256854, 0.46031971, 0.90539699, 0.46058403,
       0.11447099, 0.87562827, 0.96981444, 0.74858002, 0.8841397 ,
       0.08889962, 0.12928962, 0.23469773, 0.16247751, 0.38339818,
       0.31666934, 0.03181257, 0.75619275, 0.48845643, 0.26407046,
       0.93013376, 0.40573   , 0.41623863, 0.67291804, 0.97239935,
       0.49747645, 0.36036872, 0.77465407, 0.63928393, 0.04370449,
       0.95108063, 0.33890617, 0.18834179, 0.75448241, 0.90670328,
       0.95845807, 0.22186958, 0.99428595, 0.59133153, 0.24317084,
       0.2586122 , 0.64806609, 0.80751566, 0.79503891, 0.92311536,
       0.3728036 , 0.94905564, 0.26745403, 0.9630474 , 0.28410254,
       0.32469894, 0.92980756, 0.81881394, 0.88569977, 0.90883

In [33]:
# 
fpr,tpr,thresholds = roc_curve(y_test,y_score )

In [34]:
thresholds

array([       inf, 0.99581953, 0.96021189, 0.95946455, 0.88829261,
       0.88569977, 0.87562827, 0.87290758, 0.86063033, 0.84578967,
       0.7978056 , 0.79503891, 0.78079049, 0.77476485, 0.76306297,
       0.74403077, 0.70347968, 0.69721157, 0.68192594, 0.66383196,
       0.62330971, 0.61887387, 0.59133153, 0.57977649, 0.51452187,
       0.49747645, 0.48136495, 0.46566769, 0.45849805, 0.43868758,
       0.40573   , 0.39415026, 0.3728036 , 0.35803774, 0.35030719,
       0.34452809, 0.33916678, 0.33890617, 0.32469894, 0.28410254,
       0.27020997, 0.22633552, 0.22273579, 0.22231926, 0.22186958,
       0.11447099, 0.1026634 , 0.08889962, 0.04370449, 0.02889611])

In [35]:
fpr

array([0.        , 0.01010101, 0.1010101 , 0.1010101 , 0.34343434,
       0.34343434, 0.4040404 , 0.4040404 , 0.44444444, 0.44444444,
       0.52525253, 0.52525253, 0.55555556, 0.55555556, 0.58585859,
       0.58585859, 0.64646465, 0.64646465, 0.66666667, 0.66666667,
       0.72727273, 0.72727273, 0.73737374, 0.73737374, 0.78787879,
       0.78787879, 0.82828283, 0.82828283, 0.85858586, 0.85858586,
       0.88888889, 0.88888889, 0.90909091, 0.90909091, 0.91919192,
       0.91919192, 0.92929293, 0.92929293, 0.93939394, 0.93939394,
       0.95959596, 0.95959596, 0.96969697, 0.96969697, 0.97979798,
       0.97979798, 0.98989899, 0.98989899, 1.        , 1.        ])

In [36]:
tpr

array([0.        , 0.        , 0.        , 0.01818182, 0.01818182,
       0.03636364, 0.03636364, 0.05454545, 0.05454545, 0.10909091,
       0.10909091, 0.12727273, 0.12727273, 0.14545455, 0.14545455,
       0.23636364, 0.23636364, 0.25454545, 0.25454545, 0.29090909,
       0.29090909, 0.30909091, 0.30909091, 0.32727273, 0.32727273,
       0.34545455, 0.34545455, 0.36363636, 0.36363636, 0.4       ,
       0.4       , 0.41818182, 0.41818182, 0.45454545, 0.45454545,
       0.47272727, 0.47272727, 0.49090909, 0.49090909, 0.54545455,
       0.54545455, 0.70909091, 0.70909091, 0.72727273, 0.72727273,
       0.92727273, 0.92727273, 0.96363636, 0.96363636, 1.        ])

In [50]:
import plotly.graph_objects as go
import numpy as np


# Generate a trace for ROC curve
trace0 = go.Scatter(
    x=tpr,
    y=fpr,
    mode='lines',
    name='ROC curve'
)

# Only label every nth point to avoid cluttering
n = 10  
indices = np.arange(len(thresholds)) % n == 0  # Choose indices where index mod n is 0

trace1 = go.Scatter(
    x=tpr[indices], 
    y=fpr[indices], 
    mode='markers+text', 
    name='Threshold points', 
    text=[f"Thr={thr:.2f}" for thr in thresholds[indices]], 
    textposition='top center'
)


# Diagonal line
trace2 = go.Scatter(
    x=[0, 1], 
    y=[0, 1], 
    mode='lines', 
    name='Random (Area = 0.5)', 
    line=dict(dash='dash')
)

data = [trace0, trace1, trace2]

# Define layout with square aspect ratio
layout = go.Layout(
    title='Receiver Operating Characteristic',
    xaxis=dict(title='False Positive Rate'),
    yaxis=dict(title='True Positive Rate'),
    autosize=False,
    width=800,
    height=800,
    showlegend=False
)

# Define figure and add data
fig = go.Figure(data= data, layout=layout)

# Show figure
fig.show()