In [46]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

In [47]:
from sklearn.metrics import accuracy_score,mean_absolute_error,mean_squared_error,r2_score

In [48]:
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression
from sklearn.datasets import load_diabetes

In [49]:
d = load_diabetes()

In [50]:
d

{'data': array([[ 0.03807591,  0.05068012,  0.06169621, ..., -0.00259226,
          0.01990842, -0.01764613],
        [-0.00188202, -0.04464164, -0.05147406, ..., -0.03949338,
         -0.06832974, -0.09220405],
        [ 0.08529891,  0.05068012,  0.04445121, ..., -0.00259226,
          0.00286377, -0.02593034],
        ...,
        [ 0.04170844,  0.05068012, -0.01590626, ..., -0.01107952,
         -0.04687948,  0.01549073],
        [-0.04547248, -0.04464164,  0.03906215, ...,  0.02655962,
          0.04452837, -0.02593034],
        [-0.04547248, -0.04464164, -0.0730303 , ..., -0.03949338,
         -0.00421986,  0.00306441]]),
 'target': array([151.,  75., 141., 206., 135.,  97., 138.,  63., 110., 310., 101.,
         69., 179., 185., 118., 171., 166., 144.,  97., 168.,  68.,  49.,
         68., 245., 184., 202., 137.,  85., 131., 283., 129.,  59., 341.,
         87.,  65., 102., 265., 276., 252.,  90., 100.,  55.,  61.,  92.,
        259.,  53., 190., 142.,  75., 142., 155., 225.,  59

In [51]:
df = pd.DataFrame(d.data, columns = d.feature_names)

In [52]:
df['Target'] = d.target

In [53]:
df.shape

(442, 11)

In [54]:
df.head()

age       sex       bmi        bp        s1        s2        s3  \
0  0.038076  0.050680  0.061696  0.021872 -0.044223 -0.034821 -0.043401   
1 -0.001882 -0.044642 -0.051474 -0.026328 -0.008449 -0.019163  0.074412   
2  0.085299  0.050680  0.044451 -0.005671 -0.045599 -0.034194 -0.032356   
3 -0.089063 -0.044642 -0.011595 -0.036656  0.012191  0.024991 -0.036038   
4  0.005383 -0.044642 -0.036385  0.021872  0.003935  0.015596  0.008142   

         s4        s5        s6  Target  
0 -0.002592  0.019908 -0.017646   151.0  
1 -0.039493 -0.068330 -0.092204    75.0  
2 -0.002592  0.002864 -0.025930   141.0  
3  0.034309  0.022692 -0.009362   206.0  
4 -0.002592 -0.031991 -0.046641   135.0

In [56]:
X,y = load_diabetes(return_X_y=True)

In [10]:
x = df.iloc[:,0:10]
y = df.iloc[:,10:]

In [11]:
x.head()

age       sex       bmi        bp        s1        s2        s3  \
0  0.038076  0.050680  0.061696  0.021872 -0.044223 -0.034821 -0.043401   
1 -0.001882 -0.044642 -0.051474 -0.026328 -0.008449 -0.019163  0.074412   
2  0.085299  0.050680  0.044451 -0.005671 -0.045599 -0.034194 -0.032356   
3 -0.089063 -0.044642 -0.011595 -0.036656  0.012191  0.024991 -0.036038   
4  0.005383 -0.044642 -0.036385  0.021872  0.003935  0.015596  0.008142   

         s4        s5        s6  
0 -0.002592  0.019908 -0.017646  
1 -0.039493 -0.068330 -0.092204  
2 -0.002592  0.002864 -0.025930  
3  0.034309  0.022692 -0.009362  
4 -0.002592 -0.031991 -0.046641

In [12]:
y.head()

Target
0   151.0
1    75.0
2   141.0
3   206.0
4   135.0

In [13]:
x.shape

(442, 10)

In [14]:
y.shape

(442, 1)

In [57]:
x_train,x_test,y_train,y_test = train_test_split(X,y, test_size = 0.2, random_state= 2)

In [58]:
x_train.shape

(353, 10)

In [59]:
y_train.shape

(353,)

In [61]:
y_train

array([ 48., 276.,  47., 175.,  60.,  81., 242., 197., 137., 129., 138.,
       160., 116., 101., 147., 100., 144.,  69., 219., 107., 168., 236.,
       109., 321., 128.,  43.,  72.,  55., 141., 283.,  59., 150., 346.,
       124., 186., 308., 272., 190.,  63.,  91.,  72.,  65., 158.,  90.,
       185.,  45., 199., 206.,  61., 139., 296., 281., 122.,  95.,  40.,
       127., 145., 108., 185.,  53., 132., 101., 263.,  94., 295., 259.,
       232., 124.,  77., 102.,  96.,  83., 263.,  71., 246.,  66., 115.,
       222.,  93., 129., 128., 163.,  99.,  92., 179., 140.,  94.,  97.,
       174.,  61., 202., 135.,  88., 152.,  69.,  31., 248., 275.,  64.,
        94.,  99., 109.,  90.,  37., 164., 274., 200.,  49., 214.,  85.,
       154., 134., 164., 189.,  64., 150., 245.,  67., 265., 151.,  75.,
       208., 292.,  90.,  59.,  44., 277.,  67.,  72., 182., 135., 275.,
        95., 332., 214.,  53., 141., 102.,  88.,  74., 103., 292.,  70.,
       138., 139.,  98.,  72.,  25.,  72., 264.,  9

In [62]:
x_test.shape

(89, 10)

In [63]:
y_test.shape

(89,)

In [65]:
y_test

array([ 73., 233.,  97., 111., 277., 341.,  64.,  68.,  65., 178., 142.,
        77., 244., 115., 258.,  87., 220.,  86.,  74., 132., 136., 220.,
        91., 235., 148., 317., 131.,  84.,  65., 217., 306.,  79., 158.,
        54., 123., 174., 237., 212., 179., 281., 187., 200.,  68., 163.,
       141., 202., 178., 242.,  47., 131., 243., 142., 200.,  89., 232.,
        55., 253., 128., 104., 184., 110., 198.,  81., 195., 150.,  63.,
       151., 233., 178.,  84., 237., 109., 131., 252., 200., 160., 200.,
        51., 111.,  77., 201.,  88.,  78., 243., 268.,  55., 270., 288.,
        91.])

# This procesudure  is done with the help of Skitlearn

In [66]:
lr = LinearRegression()

In [67]:
lr.fit(x_train,y_train)

LinearRegression()

In [68]:
y_pred = lr.predict(x_test)

In [69]:
y_pred

array([154.1235067 , 204.81721599, 124.92988001, 106.09339576,
       258.53035681, 256.32953702, 118.75258786, 119.52147402,
       101.50717468, 190.54137158, 141.70360267, 172.51631204,
       174.34089304, 134.81184017, 294.13950798,  94.11403289,
       211.97052873, 156.49984762, 134.20709632, 119.62534726,
       148.88045343, 165.00378118, 151.09977307, 176.03719872,
       133.27651748, 221.29531227, 197.17482787,  96.15923158,
        50.26531577, 230.48342249, 242.06266394, 114.1153262 ,
        67.0785352 ,  94.53179042, 201.21593262, 167.05306138,
       159.87838519, 192.78601513, 114.49291816, 233.4825497 ,
       140.82309666, 121.06814332, 192.27431013, 191.13157307,
       179.1698153 , 148.35140027, 163.47610288, 276.81203359,
       100.17813072, 164.11265163, 255.81074398, 136.94979051,
       152.37507828, 107.92662528, 194.21661635,  77.35015426,
       118.50951725,  68.38527563, 154.29094022, 162.48905632,
       168.36590928, 156.8764705 ,  97.13958436, 238.17

In [70]:
lr.coef_.reshape(10,1)

array([[  -9.16088483],
       [-205.46225988],
       [ 516.68462383],
       [ 340.62734108],
       [-895.54360867],
       [ 561.21453306],
       [ 153.88478595],
       [ 126.73431596],
       [ 861.12139955],
       [  52.41982836]])

In [71]:
lr.coef_.shape

(10,)

In [72]:
lr.intercept_

151.88334520854633

In [73]:
r2_score(y_test,y_pred)

0.4399387660024644

In [131]:
class GDRegressor:
    
    def __init__(self,learning_rate = 0.01,epochs=100):
        
        self.coef_ = None
        self.intercept_ = None
        self.lr = learning_rate
        self.epochs = epochs
        
    def fit(self,X_train,y_train):
        # init our coeffs
        self.intercept_ =0
        self.coef_ = np.ones(x_train.shape[1])
        
        for i in range(self.epochs):
            #update all the coef and intercept
            y_pred = np.dot(x_train,self.coef_)  + self.intercept_
        
            intercept_der = -2 * np.mean(y_train-y_pred)
            self.intercept_ = self.intercept_ - (self.lr * intercept_der)
            coef_der = -2 * np.dot((y_train -y_pred),x_train)/x_train.shape[0]
            self.coef_ = self.coef_ - (self.lr *coef_der)
        print(self.intercept_,self.coef_)
        
    def predict(self,x_test):
        return np.dot(x_test,self.coef_) + self.intercept_

In [132]:
gdr =GDRegressor(epochs=10000,learning_rate = 0.005)

In [133]:
gdr.fit(x_train,y_train)

151.5317428869284 [ 50.58290913  -0.94742452 164.95926558 124.479167    40.86768644
  25.28930284 -96.25184652  93.89307087 157.81645156  87.26158984]


In [134]:
y_pred = gdr.predict(x_test)

In [135]:
r2_score(y_test,y_pred)

0.3197234967894512