In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt


In [9]:
from sklearn.datasets  import load_diabetes

In [16]:
dia = load_diabetes()

In [17]:
df = pd.DataFrame(dia.data, columns = dia.feature_names )

In [19]:
df['target'] = dia.target

In [20]:
df.head()

age       sex       bmi        bp        s1        s2        s3  \
0  0.038076  0.050680  0.061696  0.021872 -0.044223 -0.034821 -0.043401   
1 -0.001882 -0.044642 -0.051474 -0.026328 -0.008449 -0.019163  0.074412   
2  0.085299  0.050680  0.044451 -0.005671 -0.045599 -0.034194 -0.032356   
3 -0.089063 -0.044642 -0.011595 -0.036656  0.012191  0.024991 -0.036038   
4  0.005383 -0.044642 -0.036385  0.021872  0.003935  0.015596  0.008142   

         s4        s5        s6  target  
0 -0.002592  0.019908 -0.017646   151.0  
1 -0.039493 -0.068330 -0.092204    75.0  
2 -0.002592  0.002864 -0.025930   141.0  
3  0.034309  0.022692 -0.009362   206.0  
4 -0.002592 -0.031991 -0.046641   135.0

In [22]:
df.columns

Index(['age', 'sex', 'bmi', 'bp', 's1', 's2', 's3', 's4', 's5', 's6',
       'target'],
      dtype='object')

In [23]:
df.shape

(442, 11)

In [24]:
df.describe()

age           sex           bmi            bp            s1  \
count  4.420000e+02  4.420000e+02  4.420000e+02  4.420000e+02  4.420000e+02   
mean  -3.634285e-16  1.308343e-16 -8.045349e-16  1.281655e-16 -8.835316e-17   
std    4.761905e-02  4.761905e-02  4.761905e-02  4.761905e-02  4.761905e-02   
min   -1.072256e-01 -4.464164e-02 -9.027530e-02 -1.123996e-01 -1.267807e-01   
25%   -3.729927e-02 -4.464164e-02 -3.422907e-02 -3.665645e-02 -3.424784e-02   
50%    5.383060e-03 -4.464164e-02 -7.283766e-03 -5.670611e-03 -4.320866e-03   
75%    3.807591e-02  5.068012e-02  3.124802e-02  3.564384e-02  2.835801e-02   
max    1.107267e-01  5.068012e-02  1.705552e-01  1.320442e-01  1.539137e-01   

                 s2            s3            s4            s5            s6  \
count  4.420000e+02  4.420000e+02  4.420000e+02  4.420000e+02  4.420000e+02   
mean   1.327024e-16 -4.574646e-16  3.777301e-16 -3.830854e-16 -3.412882e-16   
std    4.761905e-02  4.761905e-02  4.761905e-02  4.761905e-02  4.761905e-02   
min   -1.156131e-01 -1.023071e-01 -7.639450e-02 -1.260974e-01 -1.377672e-01   
25%   -3.035840e-02 -3.511716e-02 -3.949338e-02 -3.324879e-02 -3.317903e-02   
50%   -3.819065e-03 -6.584468e-03 -2.592262e-03 -1.947634e-03 -1.077698e-03   
75%    2.984439e-02  2.931150e-02  3.430886e-02  3.243323e-02  2.791705e-02   
max    1.987880e-01  1.811791e-01  1.852344e-01  1.335990e-01  1.356118e-01   

           target  
count  442.000000  
mean   152.133484  
std     77.093005  
min     25.000000  
25%     87.000000  
50%    140.500000  
75%    211.500000  
max    346.000000

In [25]:
df.describe().T

count          mean        std        min        25%         50%  \
age     442.0 -3.634285e-16   0.047619  -0.107226  -0.037299    0.005383   
sex     442.0  1.308343e-16   0.047619  -0.044642  -0.044642   -0.044642   
bmi     442.0 -8.045349e-16   0.047619  -0.090275  -0.034229   -0.007284   
bp      442.0  1.281655e-16   0.047619  -0.112400  -0.036656   -0.005671   
s1      442.0 -8.835316e-17   0.047619  -0.126781  -0.034248   -0.004321   
s2      442.0  1.327024e-16   0.047619  -0.115613  -0.030358   -0.003819   
s3      442.0 -4.574646e-16   0.047619  -0.102307  -0.035117   -0.006584   
s4      442.0  3.777301e-16   0.047619  -0.076395  -0.039493   -0.002592   
s5      442.0 -3.830854e-16   0.047619  -0.126097  -0.033249   -0.001948   
s6      442.0 -3.412882e-16   0.047619  -0.137767  -0.033179   -0.001078   
target  442.0  1.521335e+02  77.093005  25.000000  87.000000  140.500000   

               75%         max  
age       0.038076    0.110727  
sex       0.050680    0.050680  
bmi       0.031248    0.170555  
bp        0.035644    0.132044  
s1        0.028358    0.153914  
s2        0.029844    0.198788  
s3        0.029312    0.181179  
s4        0.034309    0.185234  
s5        0.032433    0.133599  
s6        0.027917    0.135612  
target  211.500000  346.000000

In [26]:
df.isnull().sum()

age       0
sex       0
bmi       0
bp        0
s1        0
s2        0
s3        0
s4        0
s5        0
s6        0
target    0
dtype: int64

In [27]:
df.duplicated().sum()

0

In [42]:
x = df.iloc[:,0:10]
y = df.iloc[:,10:12]

In [43]:
x.head(2)

age       sex       bmi        bp        s1        s2        s3  \
0  0.038076  0.050680  0.061696  0.021872 -0.044223 -0.034821 -0.043401   
1 -0.001882 -0.044642 -0.051474 -0.026328 -0.008449 -0.019163  0.074412   

         s4        s5        s6  
0 -0.002592  0.019908 -0.017646  
1 -0.039493 -0.068330 -0.092204

In [37]:
x.shape

(442, 10)

In [35]:
y.head()

target
0   151.0
1    75.0
2   141.0
3   206.0
4   135.0

In [38]:
y.shape

(442, 1)

In [44]:
from sklearn.model_selection import train_test_split 

In [45]:
x_train,x_test,y_train,y_test= train_test_split(x,y, test_size = 0.2, random_state = 2)

In [46]:
x_train.head()

age       sex       bmi        bp        s1        s2        s3  \
70  -0.001882 -0.044642 -0.069797 -0.012556 -0.000193 -0.009143  0.070730   
37  -0.009147 -0.044642  0.011039 -0.057314 -0.024960 -0.042963  0.030232   
170  0.023546  0.050680 -0.020218 -0.036656 -0.013953 -0.015092  0.059685   
400 -0.023677 -0.044642  0.045529  0.090730 -0.018080 -0.035447  0.070730   
286 -0.038207 -0.044642 -0.054707 -0.077971 -0.033216 -0.086490  0.140681   

           s4        s5        s6  
70  -0.039493 -0.062913  0.040343  
37  -0.039493  0.017037 -0.005220  
170 -0.039493 -0.096433 -0.017646  
400 -0.039493 -0.034524 -0.009362  
286 -0.076395 -0.019197 -0.005220

In [47]:
x_train.shape

(353, 10)

In [48]:
y_train.shape

(353, 1)

In [49]:
x_test.shape

(89, 10)

In [50]:
y_test.shape

(89, 1)

In [51]:
from sklearn.linear_model import LinearRegression


In [52]:
lr = LinearRegression()

In [53]:
lr.fit(x_train,y_train)

LinearRegression()

In [54]:
y_pred = lr.predict(x_test)

In [62]:
y_pred.shape

(89, 1)

In [63]:
y_pred

array([[154.1235067 ],
       [204.81721599],
       [124.92988001],
       [106.09339576],
       [258.53035681],
       [256.32953702],
       [118.75258786],
       [119.52147402],
       [101.50717468],
       [190.54137158],
       [141.70360267],
       [172.51631204],
       [174.34089304],
       [134.81184017],
       [294.13950798],
       [ 94.11403289],
       [211.97052873],
       [156.49984762],
       [134.20709632],
       [119.62534726],
       [148.88045343],
       [165.00378118],
       [151.09977307],
       [176.03719872],
       [133.27651748],
       [221.29531227],
       [197.17482787],
       [ 96.15923158],
       [ 50.26531577],
       [230.48342249],
       [242.06266394],
       [114.1153262 ],
       [ 67.0785352 ],
       [ 94.53179042],
       [201.21593262],
       [167.05306138],
       [159.87838519],
       [192.78601513],
       [114.49291816],
       [233.4825497 ],
       [140.82309666],
       [121.06814332],
       [192.27431013],
       [191

In [65]:
y_test.values

array([[ 73.],
       [233.],
       [ 97.],
       [111.],
       [277.],
       [341.],
       [ 64.],
       [ 68.],
       [ 65.],
       [178.],
       [142.],
       [ 77.],
       [244.],
       [115.],
       [258.],
       [ 87.],
       [220.],
       [ 86.],
       [ 74.],
       [132.],
       [136.],
       [220.],
       [ 91.],
       [235.],
       [148.],
       [317.],
       [131.],
       [ 84.],
       [ 65.],
       [217.],
       [306.],
       [ 79.],
       [158.],
       [ 54.],
       [123.],
       [174.],
       [237.],
       [212.],
       [179.],
       [281.],
       [187.],
       [200.],
       [ 68.],
       [163.],
       [141.],
       [202.],
       [178.],
       [242.],
       [ 47.],
       [131.],
       [243.],
       [142.],
       [200.],
       [ 89.],
       [232.],
       [ 55.],
       [253.],
       [128.],
       [104.],
       [184.],
       [110.],
       [198.],
       [ 81.],
       [195.],
       [150.],
       [ 63.],
       [15

In [55]:
from sklearn.metrics import accuracy_score,r2_score

In [74]:
r2 = r2_score(y_test,y_pred)

In [75]:
r2

0.4399387660024645

In [58]:
lr.coef_

array([[  -9.16088483, -205.46225988,  516.68462383,  340.62734108,
        -895.54360867,  561.21453306,  153.88478595,  126.73431596,
         861.12139955,   52.41982836]])

In [59]:
lr.intercept_

array([151.88334521])

In [68]:
from sklearn.metrics import mean_absolute_error,mean_squared_error

In [69]:
mean_absolute_error(y_test,y_pred)

45.21292481299676

In [70]:
mean_squared_error(y_test,y_pred)

3094.4295991207023

In [72]:
RMSE = np.sqrt(mean_squared_error(y_test,y_pred))

In [73]:
RMSE

55.62759745954073

In [76]:
# Adjusted r2 score
1-((1-r2)*(40-1)/(40-1-1))

0.4252003124762136