In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.datasets import load_diabetes
from sklearn.metrics import r2_score,mean_absolute_error,mean_squared_error
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression

In [2]:
d = load_diabetes()

In [3]:
d

{'data': array([[ 0.03807591,  0.05068012,  0.06169621, ..., -0.00259226,
          0.01990842, -0.01764613],
        [-0.00188202, -0.04464164, -0.05147406, ..., -0.03949338,
         -0.06832974, -0.09220405],
        [ 0.08529891,  0.05068012,  0.04445121, ..., -0.00259226,
          0.00286377, -0.02593034],
        ...,
        [ 0.04170844,  0.05068012, -0.01590626, ..., -0.01107952,
         -0.04687948,  0.01549073],
        [-0.04547248, -0.04464164,  0.03906215, ...,  0.02655962,
          0.04452837, -0.02593034],
        [-0.04547248, -0.04464164, -0.0730303 , ..., -0.03949338,
         -0.00421986,  0.00306441]]),
 'target': array([151.,  75., 141., 206., 135.,  97., 138.,  63., 110., 310., 101.,
         69., 179., 185., 118., 171., 166., 144.,  97., 168.,  68.,  49.,
         68., 245., 184., 202., 137.,  85., 131., 283., 129.,  59., 341.,
         87.,  65., 102., 265., 276., 252.,  90., 100.,  55.,  61.,  92.,
        259.,  53., 190., 142.,  75., 142., 155., 225.,  59

In [4]:
df = pd.DataFrame(d.data, columns = d.feature_names )

In [5]:
df.head(1)

age      sex       bmi        bp        s1        s2        s3  \
0  0.038076  0.05068  0.061696  0.021872 -0.044223 -0.034821 -0.043401   

         s4        s5        s6  
0 -0.002592  0.019908 -0.017646

In [6]:
df['Target'] = d.target

In [7]:
df.shape

(442, 11)

In [8]:
df.head(1)

age      sex       bmi        bp        s1        s2        s3  \
0  0.038076  0.05068  0.061696  0.021872 -0.044223 -0.034821 -0.043401   

         s4        s5        s6  Target  
0 -0.002592  0.019908 -0.017646   151.0

In [9]:
x = df.iloc[:,:10]
y = df.iloc[:,-1]

In [10]:
x.head(1)

age      sex       bmi        bp        s1        s2        s3  \
0  0.038076  0.05068  0.061696  0.021872 -0.044223 -0.034821 -0.043401   

         s4        s5        s6  
0 -0.002592  0.019908 -0.017646

In [11]:
y.head(1)

0    151.0
Name: Target, dtype: float64

In [12]:
x_train,x_test,y_train,y_test = train_test_split(x,y,test_size = 0.2,random_state = 2)

In [13]:
x_train.shape

(353, 10)

In [14]:
y_train.shape

(353,)

In [15]:
x_test.shape

(89, 10)

In [16]:
y_test.shape

(89,)

In [17]:
lr = LinearRegression()

In [18]:
lr.fit(x_train,y_train)

LinearRegression()

In [19]:
y_pred = lr.predict(x_test)

In [20]:
r2_score(y_test,y_pred)

0.4399387660024644

In [21]:
lr.coef_

array([  -9.16088483, -205.46225988,  516.68462383,  340.62734108,
       -895.54360867,  561.21453306,  153.88478595,  126.73431596,
        861.12139955,   52.41982836])

In [22]:
lr.intercept_

151.88334520854633

# From craete class manually

In [60]:
import random
X,y1 = load_diabetes(return_X_y=True)

In [55]:
X_train,X_test,y1_train,y1_test = train_test_split(X,y1,test_size=0.2,random_state=2)

In [56]:
 import random

class MBGDRegressor:
    
    def __init__(self,batch_size,learning_rate=0.01,epochs=100):
        
        self.coef_ = None
        self.intercept_ = None
        self.lr = learning_rate
        self.epochs = epochs
        self.batch_size = batch_size
        
    def fit(self,X_train,y1_train):
        # init your coefs
        self.intercept_ = 0
        self.coef_ = np.ones(X_train.shape[1])
        
        for i in range(self.epochs):
            
            for j in range(int(X_train.shape[0]/self.batch_size)):
                
                idx = random.sample(range(X_train.shape[0]),self.batch_size)
                
                y_hat = np.dot(X_train[idx],self.coef_) + self.intercept_
                #print("Shape of y_hat",y_hat.shape)
                intercept_der = -2 * np.mean(y1_train[idx] - y_hat)
                self.intercept_ = self.intercept_ - (self.lr * intercept_der)

                coef_der = -2 * np.dot((y1_train[idx] - y_hat),X_train[idx])
                self.coef_ = self.coef_ - (self.lr * coef_der)
        
        print(self.intercept_,self.coef_)
    
    def predict(self,X_test):
        return np.dot(X_test,self.coef_) + self.intercept_



In [61]:
mbr = MBGDRegressor(batch_size=int(X_train.shape[0]/50),learning_rate=0.01,epochs=100)

In [62]:
mbr.fit(X_train,y1_train)

155.15763010679635 [  39.37410611 -135.23297603  457.25623226  304.46258117  -23.81294343
  -91.2772662  -196.79918589  117.23412828  407.1822258   117.96965523]


# from sklearn we calculate

In [30]:
from sklearn.linear_model import SGDRegressor

In [31]:
sgd = SGDRegressor(learning_rate  = 'constant',eta0= 0.2)

In [47]:
batch_size = 35

for i in range(100):
    
    idx = random.sample(range(X_train.shape[0]),batch_size)
    sgd.partial_fit(X_train[idx],y1_train[idx])
   

In [50]:
sgd.coef_

array([  28.86943149, -117.17758204,  445.34061232,  292.89870198,
        -24.70699093,  -84.66751229, -205.35694952,  135.54470361,
        392.34257715,  149.98564315])

In [51]:
sgd.intercept_

array([144.93106292])

In [52]:
y_pred = sgd.predict(X_test)

In [54]:
r2_score(y1_test,y_pred)

0.44271216169809213