In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from sklearn.linear_model import LinearRegression
from sklearn.model_selection import train_test_split
from sklearn.metrics import r2_score,mean_absolute_error,mean_squared_error
from sklearn.datasets import load_diabetes

In [2]:
d = load_diabetes()

In [4]:
d

{'data': array([[ 0.03807591,  0.05068012,  0.06169621, ..., -0.00259226,
          0.01990842, -0.01764613],
        [-0.00188202, -0.04464164, -0.05147406, ..., -0.03949338,
         -0.06832974, -0.09220405],
        [ 0.08529891,  0.05068012,  0.04445121, ..., -0.00259226,
          0.00286377, -0.02593034],
        ...,
        [ 0.04170844,  0.05068012, -0.01590626, ..., -0.01107952,
         -0.04687948,  0.01549073],
        [-0.04547248, -0.04464164,  0.03906215, ...,  0.02655962,
          0.04452837, -0.02593034],
        [-0.04547248, -0.04464164, -0.0730303 , ..., -0.03949338,
         -0.00421986,  0.00306441]]),
 'target': array([151.,  75., 141., 206., 135.,  97., 138.,  63., 110., 310., 101.,
         69., 179., 185., 118., 171., 166., 144.,  97., 168.,  68.,  49.,
         68., 245., 184., 202., 137.,  85., 131., 283., 129.,  59., 341.,
         87.,  65., 102., 265., 276., 252.,  90., 100.,  55.,  61.,  92.,
        259.,  53., 190., 142.,  75., 142., 155., 225.,  59

In [5]:
df = pd.DataFrame(d.data,columns = d.feature_names)

In [6]:
df['Target'] = d.target

In [7]:
df.shape

(442, 11)

In [8]:
df.head(2)

age       sex       bmi        bp        s1        s2        s3  \
0  0.038076  0.050680  0.061696  0.021872 -0.044223 -0.034821 -0.043401   
1 -0.001882 -0.044642 -0.051474 -0.026328 -0.008449 -0.019163  0.074412   

         s4        s5        s6  Target  
0 -0.002592  0.019908 -0.017646   151.0  
1 -0.039493 -0.068330 -0.092204    75.0

In [14]:
x = df.iloc[:,:10]
y = df.iloc[:,-1]

In [16]:
x.head(2)

age       sex       bmi        bp        s1        s2        s3  \
0  0.038076  0.050680  0.061696  0.021872 -0.044223 -0.034821 -0.043401   
1 -0.001882 -0.044642 -0.051474 -0.026328 -0.008449 -0.019163  0.074412   

         s4        s5        s6  
0 -0.002592  0.019908 -0.017646  
1 -0.039493 -0.068330 -0.092204

In [19]:
y.head(2)

0    151.0
1     75.0
Name: Target, dtype: float64

In [21]:
x_train,x_test,y_train,y_test = train_test_split(x,y,test_size = 0.2,random_state = 2)

In [22]:
x_train.shape

(353, 10)

In [23]:
x_test.shape

(89, 10)

In [24]:
y_test.shape

(89,)

In [25]:
y_train.shape

(353,)

In [37]:
lr = LinearRegression()

In [38]:
lr.fit(x_train,y_train)

LinearRegression()

In [103]:
y_pred1 = lr.predict(x_test)

In [104]:
r2_score(y_test,y_pred1)

0.4399387660024644

In [41]:
lr.coef_

array([  -9.16088483, -205.46225988,  516.68462383,  340.62734108,
       -895.54360867,  561.21453306,  153.88478595,  126.73431596,
        861.12139955,   52.41982836])

In [42]:
lr.intercept_

151.88334520854633

In [132]:
class SGDRegressor:
    
    def __init__(self,learning_rate = 0.01,epochs=100):
        
        self.coef_ = None
        self.intercept_ = None
        self.lr = learning_rate
        self.epochs = epochs
        
    def fit(self,X_train,y_train):
        # init our coeffs
        self.intercept_ =0
        self.coef_ = np.ones(x_train.shape[1])
        
        for i in range(self.epochs):
            for j in range(x_train.shape[0]):
                idx = np.random.randint(0,x_train.shape[0])
                
                y_pred = np.dot(x_train.values[idx],self.coef_)  + self.intercept_
                
                print(y_pred)
                
                intercept_der = -2 * (y_train[idx]-y_pred)
                
                self.intercept_ = self.intercept_ - (self.lr * intercept_der)
                
                coef_der = -2 * np.dot((y_train[idx] -y_pred),x_train.values[idx])
                
                self.coef_ = self.coef_ - (self.lr *coef_der)      

        print(self.intercept_,self.coef_)
        
    def predict(self,x_test):
        return np.dot(x_test,self.coef_) + self.intercept_

In [133]:
sgdr =SGDRegressor(epochs=50,learning_rate = 0.01)

In [ ]:
sgdr.fit(x_train,y_train)

In [106]:
 idx = np.random.randint(0,x_train.shape[0])

In [107]:
idx

317

In [108]:
y_train[37]

276.0

In [125]:
y_pred

array([154.1235067 , 204.81721599, 124.92988001, 106.09339576,
       258.53035681, 256.32953702, 118.75258786, 119.52147402,
       101.50717468, 190.54137158, 141.70360267, 172.51631204,
       174.34089304, 134.81184017, 294.13950798,  94.11403289,
       211.97052873, 156.49984762, 134.20709632, 119.62534726,
       148.88045343, 165.00378118, 151.09977307, 176.03719872,
       133.27651748, 221.29531227, 197.17482787,  96.15923158,
        50.26531577, 230.48342249, 242.06266394, 114.1153262 ,
        67.0785352 ,  94.53179042, 201.21593262, 167.05306138,
       159.87838519, 192.78601513, 114.49291816, 233.4825497 ,
       140.82309666, 121.06814332, 192.27431013, 191.13157307,
       179.1698153 , 148.35140027, 163.47610288, 276.81203359,
       100.17813072, 164.11265163, 255.81074398, 136.94979051,
       152.37507828, 107.92662528, 194.21661635,  77.35015426,
       118.50951725,  68.38527563, 154.29094022, 162.48905632,
       168.36590928, 156.8764705 ,  97.13958436, 238.17

In [110]:
x_train.values[100]

array([-0.08906294, -0.04464164, -0.06117437, -0.02632783, -0.05523112,
       -0.05454912,  0.04127682, -0.0763945 , -0.09393565, -0.05492509])

In [111]:
np.dot(x_train.values[110],lr.coef_) 

7.269504623441243

# from sklearn import classs for Stochastic GD

In [136]:
from sklearn.linear_model import SGDRegressor

In [137]:
reg = SGDRegressor(max_iter = 100,learning_rate = 'constant',eta0=0.01)

In [138]:
reg.fit(x_train,y_train)

C:\Users\vishal\anaconda3\lib\site-packages\sklearn\linear_model\_stochastic_gradient.py:1220: ConvergenceWarning: Maximum number of iteration reached before convergence. Consider increasing max_iter to improve the fit.
  warnings.warn("Maximum number of iteration reached before "


SGDRegressor(learning_rate='constant', max_iter=100)

In [139]:
y_pred = reg.predict(x_test)

In [140]:
r2_score(y_test,y_pred)

0.4328495199381357